apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "soe-sidecar.name" . }}-soe
  labels: {{- include "soe-sidecar.labels" . | nindent 4 }}
data:
  {{ .Values.controlPlane.agentId }}.soe.json: |
{{ .Values.soe | indent 4 }}
