apiVersion: v1
kind: Service
metadata:
  name: {{ include "soe-sidecar.name" . }}
  labels: {{- include "soe-sidecar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "soe-sidecar.selectorLabels" . | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.app.port }}, targetPort: http }
